import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { unzipSync, zipSync } from 'fflate'

const pixel = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aCdwAAAAASUVORK5CYII=', 'base64')
async function place(page: Page, name: string, category: string, latitude: string) {
  await page.getByRole('button', { name: 'Add place', exact: true }).click()
  await page.getByLabel('Place name', { exact: true }).fill(name)
  await page.getByLabel('Category', { exact: true }).selectOption(category)
  await page.getByLabel('Address', { exact: true }).fill('12 Old Quarter, Hanoi')
  await page.getByLabel('Latitude', { exact: true }).fill(latitude)
  await page.getByLabel('Longitude', { exact: true }).fill('105.85')
  await page.getByLabel('Notes / what to try').fill('Try the duck noodles')
  await page.getByLabel('Vlog and photo ideas').fill('Film the chef plating')
  await page.getByLabel('Reference links').fill('https://example.com/ideas')
  await page.getByRole('button', { name: 'Save place', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
}

test('offline albums, daily plan, slideshow, full backup and print views', async ({ page, context }, info) => {
  test.setTimeout(120000)
  await page.addInitScript(() => Object.defineProperty(window, 'showSaveFilePicker', { value: undefined }))
  await page.goto('./#/trips/trip_vietnam')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('A slow road through Vietnam')
  await context.setOffline(true)
  await place(page, 'Lotus kitchen', 'restaurant', '21.03')
  await place(page, 'Riverside hotel', 'stay', '21.02')
  await place(page, 'Lake viewpoint', 'photo', '21.06')
  await page.locator('.place-list').getByRole('button', { name: /Lotus kitchen/ }).click()
  await page.locator('.upload-album input').setInputFiles(Array.from({ length: 12 }, (_, i) => ({ name: `memory-${i}.png`, mimeType: 'image/png', buffer: pixel })))
  await expect(page.locator('.album-tile')).toHaveCount(12)
  await page.getByRole('button', { name: 'Slideshow', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Next photo', exact: true }).click()
  await expect(page.locator('.slideshow-image img')).toHaveAttribute('src', /^blob:/)
  await page.getByRole('button', { name: 'Favourite', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Favourite', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Close slideshow', exact: true }).click()
  await page.getByRole('tab', { name: 'Daily plan', exact: true }).click()
  await page.getByRole('button', { name: 'Add day', exact: true }).click()
  await page.getByLabel('Accommodation for this day').selectOption({ label: 'Riverside hotel' })
  for (const name of ['Lotus kitchen', 'Lake viewpoint']) {
    await page.getByLabel('Place to schedule').selectOption({ label: name })
    await page.getByRole('button', { name: 'Add visit', exact: true }).click()
  }
  await page.getByLabel('Visit 1 time', { exact: true }).fill('12:00')
  await page.getByLabel('Visit 1 notes').fill('Table booked under Dat')
  await page.getByRole('button', { name: 'Suggest route order' }).click()
  await expect(page.locator('.route-suggestion')).toContainText('Approximate distance')
  await page.getByRole('button', { name: 'Apply suggested order' }).click()
  await page.getByRole('button', { name: 'Save day', exact: true }).click()
  await expect(page.locator('.day-card')).toContainText('Riverside hotel')
  await page.screenshot({ path: info.outputPath('day-planner.png'), fullPage: true })
  await context.setOffline(false)
  await page.reload()
  await page.getByRole('tab', { name: 'Daily plan', exact: true }).click()
  await expect(page.locator('.day-card')).toContainText('Table booked under Dat')
  await page.getByRole('link', { name: 'Print playbook', exact: true }).first().click()
  await expect(page.locator('.book-document')).toContainText('Try the duck noodles')
  await expect(page.locator('.book-document')).toContainText('Film the chef plating')
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.book-toolbar')).toBeHidden()
  await expect(page.locator('.book-day').first()).toBeVisible()
  await page.screenshot({ path: info.outputPath('playbook-print.png'), fullPage: true })
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: 'Photobook', exact: true }).click()
  await page.getByLabel('Book place').selectOption({ label: 'Lotus kitchen' })
  await expect(page.locator('.book-photo img')).toHaveCount(12)
  await page.goto('./#/profile')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export backup', exact: true }).click()
  const backup = await download
  expect(backup.suggestedFilename()).toMatch(/\.zip$/)
  const path = await backup.path()
  expect(path).toBeTruthy()
  page.on('dialog', dialog => dialog.accept())
  const damaged = unzipSync(await readFile(path!))
  const original = Object.keys(damaged).find(name => name.endsWith('/original'))!
  damaged[original][0] ^= 255
  await page.locator('input[type=file]').setInputFiles({ name: 'corrupted.zip', mimeType: 'application/zip', buffer: Buffer.from(zipSync(damaged)) })
  await expect(page.getByRole('alert')).toContainText('integrity check failed')
  const changedMetadata = unzipSync(await readFile(path!))
  const manifest = JSON.parse(Buffer.from(changedMetadata['atlas.json']).toString())
  manifest.data.trips[0].summary = 'Unexpected corruption'
  changedMetadata['atlas.json'] = Buffer.from(JSON.stringify(manifest))
  await page.locator('input[type=file]').setInputFiles({ name: 'corrupted-metadata.zip', mimeType: 'application/zip', buffer: Buffer.from(zipSync(changedMetadata)) })
  await expect(page.getByRole('alert')).toContainText('metadata integrity check failed')
  await page.goto('./#/trips/trip_vietnam')
  await page.locator('.place-list').getByRole('button', { name: /Lotus kitchen/ }).click()
  await expect(page.locator('.album-tile')).toHaveCount(12)
  await page.goto('./#/profile')
  await page.getByRole('button', { name: 'Reset sample', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Reset sample', exact: true })).toBeEnabled()
  // Erase only this isolated test browser's blobs to prove the ZIP contains originals.
  await page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>(resolve => { const req = indexedDB.open('keyval-store'); req.onsuccess = () => resolve(req.result) })
    await new Promise<void>(resolve => { const tx = db.transaction('keyval', 'readwrite'); const store = tx.objectStore('keyval'); const req = store.openCursor(); req.onsuccess = () => { const cursor = req.result; if (cursor) { if (String(cursor.key).startsWith('photo:')) cursor.delete(); cursor.continue() } }; tx.oncomplete = () => resolve() }); db.close()
  })
  await page.locator('input[type=file]').setInputFiles(path!)
  await expect(page.getByRole('button', { name: 'Import backup', exact: true })).toBeEnabled({ timeout: 20000 })
  await page.goto('./#/trips/trip_vietnam')
  await page.locator('.place-list').getByRole('button', { name: /Lotus kitchen/ }).click()
  await expect(page.locator('.album-tile')).toHaveCount(12)
  await expect.poll(() => page.locator('.album-tile img').first().evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
  await page.getByRole('tab', { name: 'Daily plan', exact: true }).click()
  await expect(page.locator('.day-card')).toContainText('Riverside hotel')
})

test('phone city workflow works without an online city lookup', async ({ page, context }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('./#/trips/trip_vietnam')
  await page.getByRole('button', { name: 'Add city', exact: true }).click()
  await context.setOffline(true)
  await page.getByLabel('City name', { exact: true }).fill('Da Nang')
  await page.getByLabel('Country', { exact: true }).fill('Vietnam')
  await page.getByLabel('City latitude', { exact: true }).fill('16.0544')
  await page.getByLabel('City longitude', { exact: true }).fill('108.2022')
  await page.getByRole('button', { name: 'Add city', exact: true }).last().click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: /CITY .*Da Nang/ }).click()
  await expect(page.getByRole('heading', { name: 'Da Nang', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('stale city and photo edits preserve newer albums and never resurrect deleted photos', async ({ page, context }) => {
  await page.goto('./#/trips/trip_vietnam')
  await page.getByRole('button', { name: 'Edit city dates & details', exact: true }).click()
  const other = await context.newPage()
  await other.goto('./#/trips/trip_vietnam')
  await place(other, 'Concurrent album', 'sight', '21.03')
  await other.locator('.place-list').getByRole('button', { name: /Concurrent album/ }).click()
  await other.locator('.upload-album input').setInputFiles({ name: 'race.png', mimeType: 'image/png', buffer: pixel })
  await expect(other.locator('.album-tile')).toHaveCount(1)
  await page.getByRole('button', { name: 'Save city', exact: true }).click()
  await page.reload()
  await page.locator('.place-list').getByRole('button', { name: /Concurrent album/ }).click()
  await expect(page.locator('.album-tile')).toHaveCount(1)
  for (const tab of [page, other]) await tab.locator('.album-tile').click()
  await page.getByLabel('Caption', { exact: true }).fill('New caption survives')
  await page.getByLabel('Photo date', { exact: true }).focus()
  await page.getByRole('button', { name: 'Close slideshow' }).click()
  // The stale tab must change only favourite, not overwrite the new caption.
  await other.getByRole('button', { name: 'Favourite', exact: true }).click()
  await expect(other.getByRole('button', { name: 'Favourite', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await page.locator('.place-list').getByRole('button', { name: /Concurrent album/ }).click()
  await page.locator('.album-tile').click()
  await expect(page.getByLabel('Caption', { exact: true })).toHaveValue('New caption survives')
  await expect(page.getByRole('button', { name: 'Favourite', exact: true })).toHaveAttribute('aria-pressed', 'true')
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Remove photo from album' }).click()
  await expect(page.locator('.album-tile')).toHaveCount(0)
  await other.getByLabel('Caption', { exact: true }).fill('Must not resurrect')
  await other.getByLabel('Photo date', { exact: true }).focus()
  await expect(other.getByRole('dialog').getByRole('alert')).toContainText('Photo changes were not saved')
  await page.reload()
  await page.locator('.place-list').getByRole('button', { name: /Concurrent album/ }).click()
  await expect(page.locator('.album-tile')).toHaveCount(0)
})
